[tool.poetry]
name = "streamlit-chatbot"
version = "0.1.0"
description = ""
authors = ["Arthur Mello <arthur.bmello@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.43.1"
openai = "^1.65.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
